spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Liu67150
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #消费者数量
        concurrency: 10
        max-concurrency: 10
        #单批消费记录条数
        prefetch: 1
        #消费值自动启动
        auto-startup: true
        #消费失败重新入队
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        #重试时间1秒一次
        initial-interval: 1000
        #重试三次
        max-attempts: 3
        #最大间隔10秒
        max-interval: 10000
        multiplier: 1.0
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.mdiai.seckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3000
  password: Liu67150
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3